# -*- coding: utf-8 -*-
"""Aplicacion

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rgaZ6YzXqwa6lx0PdLEybU6qxwVyabNc
"""
import streamlit as st
import pandas as pd
import altair as alt


st.set_page_config(page_title="Visualización de datos de Salud de España", page_icon="⚕", layout="wide")

# Subir los datos

@st.cache_data
def load_data():
    df= pd.read_csv("datos/df_final.csv")
    return df



# Crear los laterales

if "pagina_actual" not in st.session_state:
    st.session_state.pagina_actual = "Inicio"


st.sidebar.title("Menú")
if st.sidebar.button("Inicio"):
    st.session_state.pagina_actual = "Inicio"
if st.sidebar.button("Ver resultados de la encuesta"):
    st.session_state.pagina_actual = "Ver resultados de la encuesta"
if st.sidebar.button("Predecir mi precepción de salud"):
    st.session_state.pagina_actual = "Predecir mi precepción de salud"


if st.session_state.pagina_actual=="Inicio":
    st.title("Análisis y Predicción de datos de Salud")
    st.subheader("Hola! 🤓")
    st.write("Gracias por tu interés en la salud en España.")
    st.write("""Esta página te permite visualizar resultados de la [Encuesta de Salud de España 2023](https://www.sanidad.gob.es/estadEstudios/estadisticas/encuestaSaludEspana/home.htm).
    Usa el menú lateral para navegar entre: Visualización de datos y predición de tu salud""")

    st.subheader("""Datos iniciales de la encuesta""")


elif(st.session_state.pagina_actual=="Ver resultados de la encuesta"):
    st.title("Ver resultados de la encuesta")
    st.write("Aqui encontraras los resultados de la encuesta de salud de España 2023")
    st.subheader("🗺️ Haz clic en una comunidad autónoma")

elif st.session_state.pagina_actual=="Predecir mi precepción de salud":
    st.title("Predecir mi precepción de saludd")
    st.subheader("Aquí podrás predecir tu salud basados en los datos de la población en España")
    edad=st.slider("Selecciona tu edad",0,100,25)
    st.write("Tu edad es:",edad)
    actividad= st.selectbox("Cual es tu nivel de actividad física?", ["Bajo", "Ocasional", "Regular", "Sendentario"])
    if st.button("Predecir ahora!"):
      st.success("Prediccion generada")
