# -*- coding: utf-8 -*-
"""Aplicacion

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rgaZ6YzXqwa6lx0PdLEybU6qxwVyabNc
"""

# Crear  la app

!pip install streamlit
import streamlit as st

st.set_page_config(page_title="Visualización de datos de Salud de España", layout="wide")

st.title("Análisis y Predicicion de datos de Salud")

st.write("**Hola!**\"Gracias por tu interés! Usa el menú lateral para navegar en los módulos : **1. La salud en España** **2. Predice tu salud!**")